version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "7860:7860"
    environment:
      - MODEL_SERVICE_URL=http://model:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./docs:/app/docs
    depends_on:
      - model

  model:
    build:
      context: .
      dockerfile: Dockerfile.model
    ports:
      - "8000:8000"
    volumes:
      - model_cache:/root/.cache/huggingface

volumes:
  model_cache: 